# fly.toml app configuration file generated for milestone-monitor on 2023-07-02T04:51:17-04:00

app = "milestone-monitor"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[processes]
web = "pipenv run gunicorn --bind 0.0.0.0:8000 -w 2 backend.wsgi"
celery = "pipenv run celery -A backend worker --beat --concurrency 2"

[env]
  PORT = "8000"
  PINECONE_ENV = "us-east1-gcp"
  PINECONE_INDEX = "milestone-monitor"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
