# fly.toml app configuration file generated for milestone-monitor on 2023-07-02T04:51:17-04:00

app = "milestone-monitor"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[env]
  PORT = "8000"
  PINECONE_ENV = "us-east1-gcp"
  PINECONE_INDEX = "milestone-monitor"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
