# Generated by Django 4.2.1 on 2023-06-25 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.BigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(10000000000),
                            django.core.validators.MaxValueValidator(19999999999),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_time", models.TimeField(null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[
                            (0, "Hourly"),
                            (1, "Daily"),
                            (2, "Weekly"),
                            (3, "Biweekly"),
                            (4, "Monthly"),
                            (99, "Minutely"),
                        ]
                    ),
                ),
                (
                    "importance",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")]
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="milestone_monitor.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OneTimeGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_at", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="milestone_monitor.user",
                    ),
                ),
            ],
        ),
    ]
