# Generated by Django 4.2 on 2023-04-09 02:09

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0001_initial"),
    ]

    operations = [
        VectorExtension()
    ]
