# Generated by Django 4.2.2 on 2023-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimegoal",
            name="task_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
