# Generated by Django 4.2 on 2023-04-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("milestone_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringgoal",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AlterField(
            model_name="recurringgoal",
            name="frequency",
            field=models.IntegerField(
                choices=[
                    (0, "Hourly"),
                    (1, "Daily"),
                    (2, "Weekly"),
                    (3, "Montly"),
                    (4, "Minutely"),
                ]
            ),
        ),
    ]
