# Generated by Django 4.2.2 on 2023-07-01 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0002_onetimegoal_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringgoal",
            name="reminder_time",
        ),
        migrations.AddField(
            model_name="onetimegoal",
            name="importance",
            field=models.IntegerField(
                choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recurringgoal",
            name="is_running",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recurringgoal",
            name="reminder_start_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recurringgoal",
            name="end_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="recurringgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="milestone_monitor.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(10000000000),
                    django.core.validators.MaxValueValidator(19999999999),
                ],
            ),
        ),
    ]
