# Generated by Django 4.2 on 2023-04-09 02:18

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0002_migration_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimegoal",
            name="embedding",
            field=pgvector.django.VectorField(default=None, dimensions=384),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recurringgoal",
            name="embedding",
            field=pgvector.django.VectorField(default=None, dimensions=384),
            preserve_default=False,
        ),
    ]
