# Generated by Django 4.2 on 2023-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0003_onetimegoal_embedding_recurringgoal_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onetimegoal",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="recurringgoal",
            name="embedding",
        ),
        migrations.AlterField(
            model_name="recurringgoal",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
