# Generated by Django 4.2.1 on 2023-05-19 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0004_alter_recurringgoal_reminder_time"),
        ("milestone_monitor", "0004_remove_onetimegoal_embedding_and_more"),
    ]

    operations = []
