# Generated by Django 4.2.2 on 2023-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("milestone_monitor", "0004_goal_remove_recurringgoal_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="end_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="final_task_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="reminder_frequency",
            field=models.IntegerField(
                choices=[
                    (0, "Hourly"),
                    (1, "Daily"),
                    (2, "Weekly"),
                    (3, "Biweekly"),
                    (4, "Monthly"),
                    (99, "Minutely"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="reminder_start_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
