# Generated by Django 4.2.3 on 2023-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "milestone_monitor",
            "0005_alter_goal_end_at_alter_goal_final_task_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="final_task_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
